### PR TITLE
fixes potential memory leaks in file ccn-lite-rpc.c

### LINKED ISSUE #339: potential memory leak in ccn-lite-rpc.c
#### Description
There is a potential memory leak in ``ccn-lite-rpc.c`` in [line 368](https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-utils/src/ccn-lite-rpc.c#L368). The function allocates memory for the variable ``expr`` and ``nonce``. However, if no memory for the variable ``nonce`` can be allocated the function does not release the previously allocated memory for variable ``expr``.

#### Steps to reproduce the issue
This bug was identified by clangs static analyzer.

### PR DESCRIPTION
**Pull request by mfrey**
### Contribution description
This PR addresses three potential memory leaks identified by the ``scan-build.sh`` script (which uses clang static analyzer). In order to avoid leaking memory a check is performed if memory has been previously allocated and if true it is freed accordingly.

### Issues/PRs references
Fixes #339

### CODE REVIEW

File: src/ccnl-utils/src/ccn-lite-rpc.c [hunk 1]
```diff
@@ -175,6 +175,10 @@ parsePrefixTerm(int lev, char **cpp)
                     free(term);
                 }
 
+                if (t2) {
```
Comment (cgundogan) [inline src/ccnl-utils/src/ccn-lite-rpc.c]: is the check to `t2` really necessary? It seems that this is checked a couple of lines above?

File: src/ccnl-utils/src/ccn-lite-rpc.c [hunk 2]
```diff
@@ -365,6 +369,9 @@ main(int argc, char *argv[])
 
         nonce = calloc(1, sizeof(*nonce));
         if (!nonce) {
+            if (expr) {
```
Comment (cgundogan) [inline src/ccnl-utils/src/ccn-lite-rpc.c]: here also; is the check to `expre` necessary, given that it is checked above?

File: src/ccnl-utils/src/ccn-lite-rpc.c [hunk 3]
```diff
@@ -375,6 +382,9 @@ main(int argc, char *argv[])
 
         req = calloc(1, sizeof(*req));
         if (!req) {
+            if (expr) {
```
Comment (cgundogan) [inline src/ccnl-utils/src/ccn-lite-rpc.c]: .

File: src/ccnl-utils/src/ccn-lite-rpc.c [hunk 4]
```diff
@@ -385,6 +395,10 @@ main(int argc, char *argv[])
 
     reqlen = sizeof(tmp);
     if (ccnl_switch_prependCoding(CCNL_ENC_LOCALRPC, &reqlen, tmp, &switchlen)) {
+        if (expr) {
```
Comment (cgundogan) [inline src/ccnl-utils/src/ccn-lite-rpc.c]: .

File: src/ccnl-utils/src/ccn-lite-rpc.c (hunk 1 above)
Comment (mfrey) [reply src/ccnl-utils/src/ccn-lite-rpc.c]: I prefer to check if something is actually non-null before I try to free it. If you want we can remove the check, but given the "complexity" of the function I would prefer to leave it there.

File: src/ccnl-utils/src/ccn-lite-rpc.c (hunk 2 above)
Comment (mfrey) [reply src/ccnl-utils/src/ccn-lite-rpc.c]: Okay, I can remove the check. Putting a return -1 and omitting the curly brackets and then putting them there afterwards indicating that the if statement is somehow related to the following '{' seems a bit more concerning to me.
