### PR TITLE
fixes potential memory leak in ccn-lite-ctrl.c

### LINKED ISSUE #327: potential memory leak in main() in ccn-lite-ctrl.c
There is a potential memory leak in ``ccn-lite-ctrl.c``identified by scan-build.sh/clang static analyzer
```C
1052   udp = strdup(optarg);
...
1055   port = strtol(strtok(NULL, "/"), NULL, 0);
1056   use_udp = 1;
1057   printf("udp: <%s> <%d>\n", udp, port);
1058   break;
```

EDIT: Originally posting was about strok/strtol. Hence, the first seven replies can be ignored for this issue.

### PR DESCRIPTION
**Pull request by mfrey**
### Contribution description
The PR checks if a call to ``strdup`` failed and also introduces a new variable which stores the newly allocated memory before it is overwritten again by a call to ``strtok`` and thus, the memory allocated by ``strdup`` can't be freed anymore.

### Issues/PRs references
Fixes #327

### CODE REVIEW

File: src/ccnl-utils/src/ccn-lite-ctrl.c [hunk 1]
```diff
@@ -1627,11 +1628,21 @@ main(int argc, char *argv[])
...
+                return -1;
+            }
+
+            udp = strtok(udp_temp, "/");
             port = strtol(strtok(NULL, "/"), NULL, 0);
             use_udp = 1;
             printf("udp: <%s> <%i>\n", udp, port);
+
+            /** if memory has been allocated previously, free it */
+            if (udp_temp) {
```
Comment (cgundogan) [inline src/ccnl-utils/src/ccn-lite-ctrl.c]: Isn't `udp_temp` always non-`NULL` here? Is this check necessary?

Comment (blacksheeep) [reply src/ccnl-utils/src/ccn-lite-ctrl.c]: If Malloc returns NULL in strdup because system is out of memory it can be NULL

Comment (cgundogan) [reply src/ccnl-utils/src/ccn-lite-ctrl.c]: But there is a check for that only 9 lines above ..

Comment (blacksheeep) [reply src/ccnl-utils/src/ccn-lite-ctrl.c]: Right. Missed that. So, we can remove that.

**Comment by mfrey** [comment]
> Remove unnecessary check, see comments

Has been addressed with the latest updated commit (rebased, push -f)
