### PR TITLE
fixes ccnl_content_add2cache prefix comparison

### LINKED ISSUE #200: erroneous check for duplicate content in ccnl_content_add2cache
Hi,

I wrote a local producer function which stores content created on the fly (e.g. sensor readings) in the cache. At some point in this function, I'm calling ``ccnl_content_add2cache`` which is also used by the ``ccnl_cont`` command in RIOT. 

With some surprise I've noticed that "same" content added via  ``ccnl_content_add2cache`` is added multiple times. Same refers here to multiple entries of ``/some/interest/example => 42``, but also another interest with a different content is possible, e.g. ``/some/interest/example => 23`` (besides the previous one).

I've checked the code and apparently the check for duplicate entries is performed in ``ccnl_content_add2cache`` here:
```C
 552     for (cit = ccnl->contents; cit; cit = cit->next) {
 553         if (c == cit) {
 554             DEBUGMSG_CORE(DEBUG, "--- Already in cache ---\n");
 555             return NULL;
 556         }
 557     }
```

I don't know if it is a general misunderstanding on my behalf, but I assumed that there is a unique relationship between interest and content, so a plain interest matches exactly one content (at least for CCNx (I'm aware that NDN introduces the concept of ``ChildSelector``)). 

The ``if`` statement just checks if the same pointer is not passed to the function twice. Is it not necessary to check actually for the prefix and the content? Maybe, I'm missing the point?

TIA
 Michael

### PR DESCRIPTION
**Pull request by mfrey**
### Contribution description

This PR addresses an issue in function ``ccnl_content_add2cache `` in `` ccnl_relay.c``. Currently, the function checks if the pointer passed to the function has been added before and hence, duplicate content is added to the content store. The function replaces the comparison of pointers with a call to ``ccnl_prefix_cmp`` which checks if the prefix content to be added **exactly** matches an existing entry in the content store.

### Issues/PRs references

Fixes #200

### CODE REVIEW

File: src/ccnl-core/src/ccnl-relay.c [hunk 1]
```diff
@@ -570,8 +570,9 @@ ccnl_content_add2cache(struct ccnl_relay_s *ccnl, struct ccnl_content_s *c)
     DEBUGMSG_CORE(DEBUG, "ccnl_content_add2cache (%d/%d) --> %p = %s [%d]\n",
                   ccnl->contentcnt, ccnl->max_cache_entries,
                   (void*)c, ccnl_prefix_to_str(c->pkt->pfx,s,CCNL_MAX_PREFIX_SIZE), (c->pkt->pfx->chunknum)? *(c->pkt->pfx->chunknum) : -1);
+
     for (cit = ccnl->contents; cit; cit = cit->next) {
-        if (c == cit) {
+        if (ccnl_prefix_cmp(c->pkt->pfx, 0, cit->pkt->pfx, CMP_EXACT) == 0) {
```
Comment (cgundogan) [inline src/ccnl-core/src/ccnl-relay.c]: I know it's used somewhere else and it's probably jt a matter of taste, but for pointers I usually would expect `NULL` instead of `0` to immediately see that the parameter expects a pointer

Comment (mfrey) [reply src/ccnl-core/src/ccnl-relay.c]: My bad. This was totally unintentional.
